name: streampulse
description: Client Flutter multiplateforme (Web, iOS, Android) de diffusion audio en direct StreamPulse.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^17.2.0
  http: ^1.2.2
  flutter_secure_storage: ^10.0.0
  google_fonts: ^6.2.1
  web: ^1.1.1
  just_audio: ^0.10.6
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.2.4
  connectivity_plus: ^7.3.1
  media_kit: ^1.2.6
  media_kit_libs_ios_audio: ^1.1.4
  media_kit_libs_android_audio: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
